name = "FuhrbergerColumns"
authors = ["Vitor Cantarella, Ali Rahmani, Paul Renaudin, Lester Pide, and supervisors"]
[compat]
julia = "1.11.1"
DrWatson = "2.18.0"
[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
